### ISSUE TITLE
The house icon disappears after rotation.

### ISSUE THREAD

**Issue by ImDiM** [Wavesonics/hammer-editor#447]
Version 1.9.2 (109030000)
Issue: After rotation, the  **house** icon on the left side of Alice In Wonderland disappears.

<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/99b54e8b-96b0-494a-9c8a-f08b48c521a1" />

<img width="1280" height="576" alt="Image" src="https://github.com/user-attachments/assets/e7a563f7-9030-43f5-8a94-f1c5c23758c9" />

**Comment by Wavesonics** [comment]
it looks like you are a few versions behind, see if there is an update from where you installed it, this should be fixed.

**Comment by ImDiM** [comment]
I’m on the latest version 1.13.0, and the same issue still occurs.

**Comment by Wavesonics** [comment]
found it and fixed it, thanks @ImDiM !
